/**
 * The seed recipe corpus — authentic, hand-authored dishes that MealMesh's own
 * engine (planEngine) draws from, no external LLM. Each entry is a normalized
 * RawRecipe; `getCorpus()` tags them once (deterministically) through the SAME
 * constraint lexicon the app enforces with, so a dish's safety tokens are
 * computed by code, never declared.
 *
 * SCOPE: this is a SEED, not the finished dataset. It seeds the launch cuisines
 * (South Asian — Pakistani + Indian split — plus Chinese, Middle Eastern,
 * Mediterranean, East Asian, American, European, Latin, African). The procedural
 * generator (cuisine.ts) fills any slot the corpus can't cover, so plans are
 * always complete. New dishes drop straight in here (or, at scale, the
 * `recipe_corpus` table via migration 0013) and the engine picks them up — the path
 * to deep per-cuisine / per-country depth.
 *
 * `countryOrigin` (ISO code) disambiguates a broad cuisine: a Pakistani
 * household scores PK-origin South Asian dishes above generic ones.
 */

import { tagRecipe, type RawRecipe, type TaggedRecipe } from '@/lib/recipeCorpus';

/* Compact authoring helper — most fields default sensibly. */
const r = (
  title: string,
  cuisine: RawRecipe['cuisine'],
  course: RawRecipe['course'],
  ingredients: string[],
  steps: string[],
  opts: { country?: string; servings?: number; timeMinutes?: number } = {},
): RawRecipe => ({
  title,
  cuisine,
  course,
  ingredients: ingredients.map((name) => ({ name })),
  steps,
  countryOrigin: opts.country,
  servings: opts.servings ?? 4,
  timeMinutes: opts.timeMinutes,
  source: 'MealMesh original',
  license: 'original',
});

/** The raw, untagged seed recipes. Exported so the offline seed script
 *  (scripts/seed-corpus.ts) upserts the SAME authored list the app ships. */
export const RAW: RawRecipe[] = [
  /* ---------------- South Asian — Pakistan ---------------- */
  r('Chicken Karahi', 'south_asian', 'dinner', ['chicken', 'tomato', 'ginger', 'garlic', 'green chili', 'coriander', 'cooking oil'],
    ['Sear chicken in oil over high heat.', 'Add tomato, ginger and garlic; cook until oil separates.', 'Add green chili and spices; simmer until tender.', 'Finish with fresh coriander.'], { country: 'PK', timeMinutes: 40 }),
  r('Beef Nihari', 'south_asian', 'dinner', ['beef shank', 'wheat flour', 'ginger', 'garlic', 'nihari masala', 'cooking oil'],
    ['Brown beef shank with ginger-garlic.', 'Add nihari masala and water; slow-cook until very tender.', 'Thicken gravy with a flour slurry.', 'Garnish with ginger and serve with naan.'], { country: 'PK', timeMinutes: 180 }),
  r('Chicken Haleem', 'south_asian', 'dinner', ['chicken', 'lentils', 'wheat', 'barley', 'ginger', 'garlic', 'garam masala'],
    ['Boil chicken with lentils, wheat and barley until soft.', 'Blend to a thick, smooth porridge.', 'Temper with fried onions and spices.', 'Top with ginger, lemon and coriander.'], { country: 'PK', timeMinutes: 150 }),
  r('Aloo Gosht', 'south_asian', 'lunch', ['lamb', 'potato', 'onion', 'tomato', 'ginger', 'garlic', 'cooking oil'],
    ['Brown lamb with onion, ginger and garlic.', 'Add tomato and spices; cook to a masala.', 'Add potato and water; simmer until both are tender.', 'Serve with roti or rice.'], { country: 'PK', timeMinutes: 75 }),
  r('Chapli Kebab', 'south_asian', 'supper', ['ground beef', 'tomato', 'onion', 'green chili', 'coriander', 'cornmeal'],
    ['Mix beef with chopped tomato, onion, chili and spices.', 'Bind with a little cornmeal.', 'Flatten into wide patties.', 'Shallow-fry until crisp and browned.'], { country: 'PK', timeMinutes: 30 }),
  r('Seekh Kebab', 'south_asian', 'supper', ['ground beef', 'onion', 'ginger', 'garlic', 'green chili', 'garam masala'],
    ['Knead beef with grated onion, ginger, garlic and spices.', 'Mould around skewers.', 'Grill or pan-sear, turning, until charred.', 'Serve with chutney.'], { country: 'PK', timeMinutes: 30 }),
  r('Chicken Biryani', 'south_asian', 'lunch', ['chicken', 'basmati rice', 'yogurt', 'onion', 'ginger', 'garlic', 'biryani masala'],
    ['Marinate chicken in yogurt and spices.', 'Par-boil rice with whole spices.', 'Layer chicken masala and rice.', 'Steam on dum until fragrant.'], { country: 'PK', timeMinutes: 75 }),
  r('Chana Pulao', 'south_asian', 'lunch', ['basmati rice', 'chickpeas', 'onion', 'cumin', 'whole spices', 'cooking oil'],
    ['Fry onion and whole spices in oil.', 'Add chickpeas and rice; toss.', 'Add water and cook until fluffy.', 'Rest, then fork through.'], { country: 'PK', timeMinutes: 40 }),
  r('Daal Chawal', 'south_asian', 'lunch', ['lentils', 'rice', 'onion', 'garlic', 'cumin', 'turmeric', 'cooking oil'],
    ['Boil lentils with turmeric until creamy.', 'Make a tarka of fried garlic and cumin.', 'Pour tarka over the daal.', 'Serve over steamed rice.'], { country: 'PK', timeMinutes: 40 }),
  r('Anda Paratha', 'south_asian', 'breakfast', ['eggs', 'wheat flour', 'butter', 'green chili', 'coriander'],
    ['Roll and griddle a flaky paratha with butter.', 'Whisk eggs with chili and coriander.', 'Cook the egg into a thin omelette.', 'Fold inside the warm paratha.'], { country: 'PK', timeMinutes: 20 }),
  r('Halwa Puri', 'south_asian', 'breakfast', ['semolina', 'wheat flour', 'chickpeas', 'sugar', 'cardamom', 'cooking oil'],
    ['Cook semolina halwa with sugar and cardamom.', 'Simmer a light chickpea curry.', 'Fry puffed puris until golden.', 'Serve the three together.'], { country: 'PK', timeMinutes: 50 }),
  r('Chana Chaat', 'south_asian', 'supper', ['chickpeas', 'potato', 'onion', 'tomato', 'tamarind', 'chaat masala'],
    ['Toss boiled chickpeas and potato.', 'Add chopped onion and tomato.', 'Dress with tamarind and chaat masala.', 'Finish with lemon.'], { country: 'PK', timeMinutes: 15 }),
  r('Vegetable Samosa', 'south_asian', 'supper', ['potato', 'peas', 'wheat flour', 'cumin', 'green chili', 'cooking oil'],
    ['Make a spiced potato-and-pea filling.', 'Wrap in pastry triangles.', 'Deep-fry until crisp and golden.', 'Serve with chutney.'], { country: 'PK', timeMinutes: 45 }),
  r('Sooji Halwa', 'south_asian', 'dessert', ['semolina', 'sugar', 'ghee', 'cardamom', 'almonds'],
    ['Toast semolina in ghee until golden.', 'Add sugar syrup carefully.', 'Cook until it pulls from the pan.', 'Finish with cardamom and almonds.'], { country: 'PK', timeMinutes: 25 }),
  r('Kheer', 'south_asian', 'dessert', ['rice', 'milk', 'sugar', 'cardamom', 'pistachio'],
    ['Simmer rice in milk until thick.', 'Sweeten with sugar.', 'Add cardamom.', 'Chill and top with pistachio.'], { country: 'PK', timeMinutes: 60 }),

  /* ---------------- South Asian — India ---------------- */
  r('Masala Dosa', 'south_asian', 'breakfast', ['rice', 'lentils', 'potato', 'onion', 'curry leaves', 'mustard seeds'],
    ['Ferment a rice-and-lentil batter.', 'Make a spiced potato filling.', 'Crisp the dosa on a hot griddle.', 'Fold the filling inside.'], { country: 'IN', timeMinutes: 40 }),
  r('Idli Sambar', 'south_asian', 'breakfast', ['rice', 'lentils', 'toor dal', 'tamarind', 'sambar powder', 'vegetables'],
    ['Steam fermented idli batter into cakes.', 'Cook dal with tamarind and vegetables.', 'Season with sambar powder.', 'Serve idli with hot sambar.'], { country: 'IN', timeMinutes: 45 }),
  r('Chole', 'south_asian', 'lunch', ['chickpeas', 'onion', 'tomato', 'ginger', 'garlic', 'chole masala'],
    ['Sauté onion, ginger and garlic.', 'Add tomato and chole masala.', 'Simmer chickpeas until rich.', 'Garnish with coriander.'], { country: 'IN', timeMinutes: 50 }),
  r('Rajma Chawal', 'south_asian', 'lunch', ['kidney beans', 'rice', 'onion', 'tomato', 'ginger', 'garam masala'],
    ['Cook kidney beans until soft.', 'Build an onion-tomato masala.', 'Simmer beans in the masala.', 'Serve over rice.'], { country: 'IN', timeMinutes: 60 }),
  r('Palak Paneer', 'south_asian', 'dinner', ['spinach', 'paneer', 'onion', 'garlic', 'cream', 'garam masala'],
    ['Blanch and blend spinach.', 'Fry onion and garlic.', 'Add spinach purée and cream.', 'Fold in pan-fried paneer.'], { country: 'IN', timeMinutes: 35 }),
  r('Vegetable Pulao', 'south_asian', 'lunch', ['basmati rice', 'mixed vegetables', 'cumin', 'whole spices', 'cooking oil'],
    ['Fry whole spices and cumin.', 'Add vegetables and rice.', 'Add water and steam until fluffy.', 'Rest and serve.'], { country: 'IN', timeMinutes: 35 }),
  r('Dal Tadka', 'south_asian', 'dinner', ['lentils', 'tomato', 'garlic', 'cumin', 'turmeric', 'ghee'],
    ['Boil lentils with turmeric and tomato.', 'Make a ghee tadka of garlic and cumin.', 'Stir the tadka through.', 'Serve with rice or roti.'], { country: 'IN', timeMinutes: 35 }),
  r('Aloo Tikki', 'south_asian', 'supper', ['potato', 'peas', 'green chili', 'cumin', 'breadcrumbs'],
    ['Mash potato with peas and spices.', 'Shape into patties.', 'Coat lightly and pan-fry.', 'Serve with chutney.'], { country: 'IN', timeMinutes: 25 }),
  r('Gajar Halwa', 'south_asian', 'dessert', ['carrot', 'milk', 'sugar', 'ghee', 'cardamom', 'almonds'],
    ['Simmer grated carrot in milk.', 'Add sugar and reduce.', 'Finish with ghee and cardamom.', 'Top with almonds.'], { country: 'IN', timeMinutes: 60 }),
  r('Mango Lassi', 'south_asian', 'drink', ['yogurt', 'mango', 'sugar', 'cardamom'],
    ['Blend yogurt and mango.', 'Sweeten to taste.', 'Add a pinch of cardamom.', 'Serve chilled.'], { country: 'IN', timeMinutes: 5 }),

  /* ---------------- Chinese ---------------- */
  r('Kung Pao Chicken', 'chinese', 'dinner', ['chicken', 'peanuts', 'scallion', 'garlic', 'ginger', 'dried chili', 'soy sauce'],
    ['Sear marinated chicken.', 'Fry aromatics and dried chili.', 'Toss with a savoury-sweet sauce.', 'Stir in peanuts and serve.'], { timeMinutes: 25 }),
  r('Mapo Tofu', 'chinese', 'dinner', ['tofu', 'ground pork', 'garlic', 'ginger', 'doubanjiang', 'scallion'],
    ['Fry pork with garlic and ginger.', 'Add doubanjiang and stock.', 'Slide in cubed tofu.', 'Finish with scallion.'], { timeMinutes: 25 }),
  r('Egg Fried Rice', 'chinese', 'lunch', ['rice', 'eggs', 'scallion', 'soy sauce', 'cooking oil'],
    ['Scramble eggs in a hot wok.', 'Add day-old rice and break up.', 'Season with soy sauce.', 'Toss through scallion.'], { timeMinutes: 15 }),
  r('Chicken Chow Mein', 'chinese', 'dinner', ['noodles', 'chicken', 'cabbage', 'carrot', 'soy sauce', 'garlic'],
    ['Stir-fry chicken until done.', 'Add vegetables and garlic.', 'Toss boiled noodles with soy sauce.', 'Combine and serve hot.'], { timeMinutes: 25 }),
  r('Sweet and Sour Pork', 'chinese', 'dinner', ['pork', 'bell pepper', 'pineapple', 'onion', 'vinegar', 'sugar'],
    ['Fry battered pork until crisp.', 'Stir-fry peppers, onion and pineapple.', 'Add a sweet-sour sauce.', 'Toss the pork through.'], { timeMinutes: 35 }),
  r('Congee', 'chinese', 'breakfast', ['rice', 'ginger', 'scallion', 'soy sauce'],
    ['Simmer rice in plenty of water.', 'Cook low until silky.', 'Season with ginger and soy.', 'Top with scallion.'], { timeMinutes: 60 }),
  r('Vegetable Spring Rolls', 'chinese', 'supper', ['cabbage', 'carrot', 'scallion', 'wheat flour', 'cooking oil'],
    ['Stir-fry shredded vegetables.', 'Wrap in thin pastry.', 'Deep-fry until crisp.', 'Serve with dipping sauce.'], { timeMinutes: 40 }),
  r('Mango Pudding', 'chinese', 'dessert', ['mango', 'milk', 'sugar', 'gelatin'],
    ['Blend mango with milk and sugar.', 'Set with gelatin.', 'Chill until firm.', 'Serve cold.'], { timeMinutes: 20 }),

  /* ---------------- Middle Eastern ---------------- */
  r('Chicken Shawarma', 'middle_eastern', 'dinner', ['chicken', 'yogurt', 'garlic', 'cumin', 'coriander', 'flatbread'],
    ['Marinate chicken in yogurt and spices.', 'Roast or pan-sear until charred.', 'Slice thin.', 'Wrap in flatbread with garlic sauce.'], { timeMinutes: 40 }),
  r('Falafel', 'middle_eastern', 'supper', ['chickpeas', 'garlic', 'cumin', 'coriander', 'parsley', 'cooking oil'],
    ['Blend soaked chickpeas with herbs and spices.', 'Shape into small patties.', 'Deep-fry until crisp.', 'Serve with tahini.'], { timeMinutes: 30 }),
  r('Hummus', 'middle_eastern', 'appetizer', ['chickpeas', 'tahini', 'garlic', 'lemon', 'olive oil'],
    ['Blend chickpeas with tahini and garlic.', 'Loosen with lemon and water.', 'Whip until smooth.', 'Drizzle with olive oil.'], { timeMinutes: 15 }),
  r('Tabbouleh', 'middle_eastern', 'appetizer', ['bulgur', 'parsley', 'tomato', 'mint', 'lemon', 'olive oil'],
    ['Soak bulgur until tender.', 'Chop parsley, mint and tomato finely.', 'Toss together.', 'Dress with lemon and olive oil.'], { timeMinutes: 25 }),
  r('Lamb Kofta', 'middle_eastern', 'dinner', ['ground lamb', 'onion', 'parsley', 'cumin', 'cinnamon'],
    ['Knead lamb with onion, parsley and spices.', 'Shape around skewers.', 'Grill until charred.', 'Serve with flatbread.'], { timeMinutes: 30 }),
  r('Shakshuka', 'middle_eastern', 'breakfast', ['eggs', 'tomato', 'bell pepper', 'onion', 'cumin', 'paprika'],
    ['Simmer a spiced tomato-pepper sauce.', 'Make wells and crack in eggs.', 'Cover until just set.', 'Serve from the pan with bread.'], { timeMinutes: 25 }),
  r('Mujadara', 'middle_eastern', 'lunch', ['lentils', 'rice', 'onion', 'cumin', 'olive oil'],
    ['Cook lentils until almost done.', 'Add rice and cumin.', 'Fry onions until deep brown.', 'Fold onions through and serve.'], { timeMinutes: 45 }),
  r('Baked Fruit with Honey', 'middle_eastern', 'dessert', ['apple', 'honey', 'cinnamon', 'walnuts'],
    ['Halve and core the fruit.', 'Drizzle with honey and cinnamon.', 'Bake until soft.', 'Top with walnuts.'], { timeMinutes: 25 }),
  r('Beef Kabsa', 'middle_eastern', 'dinner', ['beef', 'basmati rice', 'tomato', 'onion', 'garlic', 'kabsa spice', 'cooking oil'],
    ['Brown beef with onion and garlic.', 'Add tomato and kabsa spice.', 'Add rice and stock.', 'Steam until fluffy.'], { country: 'SA', timeMinutes: 55 }),
  r('Chicken Mandi', 'middle_eastern', 'dinner', ['chicken', 'basmati rice', 'cardamom', 'cinnamon', 'onion', 'cooking oil'],
    ['Spice the chicken and sear.', 'Layer over soaked rice with whole spices.', 'Cover and steam low.', 'Rest, then serve.'], { country: 'SA', timeMinutes: 60 }),
  r('Ghormeh Sabzi', 'middle_eastern', 'dinner', ['lamb', 'kidney beans', 'parsley', 'fenugreek', 'dried lime', 'onion', 'cooking oil'],
    ['Fry herbs until dark and fragrant.', 'Brown lamb with onion.', 'Add beans, dried lime and water.', 'Simmer long and slow.'], { country: 'IR', timeMinutes: 90 }),
  r('Fesenjan', 'middle_eastern', 'dinner', ['chicken', 'walnuts', 'pomegranate molasses', 'onion', 'cooking oil'],
    ['Toast and grind walnuts.', 'Brown chicken with onion.', 'Add walnut paste and pomegranate molasses.', 'Simmer until rich.'], { country: 'IR', timeMinutes: 70 }),
  r('Chelo Kebab', 'middle_eastern', 'dinner', ['ground beef', 'onion', 'basmati rice', 'cumin', 'cooking oil'],
    ['Knead beef with grated onion.', 'Shape onto skewers and grill.', 'Steam buttered rice separately.', 'Serve kebab over rice.'], { country: 'IR', timeMinutes: 50 }),
  r('Koshari', 'middle_eastern', 'lunch', ['rice', 'lentils', 'macaroni pasta', 'chickpeas', 'tomato', 'onion', 'cooking oil'],
    ['Cook rice and lentils together.', 'Boil the pasta.', 'Fry onions until crisp.', 'Layer and top with tomato sauce.'], { country: 'EG', timeMinutes: 45 }),
  r('Ful Medames', 'middle_eastern', 'breakfast', ['fava beans', 'garlic', 'lemon', 'cumin', 'olive oil', 'parsley'],
    ['Warm the fava beans.', 'Mash lightly with garlic and cumin.', 'Dress with lemon and olive oil.', 'Scatter parsley.'], { country: 'EG', timeMinutes: 20 }),
  r('Molokhia', 'middle_eastern', 'lunch', ['molokhia leaves', 'chicken', 'garlic', 'coriander', 'cooking oil'],
    ['Simmer chicken to make stock.', 'Add chopped molokhia.', 'Bloom garlic and coriander in oil.', 'Stir through and serve with rice.'], { country: 'EG', timeMinutes: 50 }),
  r('Fattoush', 'middle_eastern', 'appetizer', ['lettuce', 'tomato', 'cucumber', 'pita', 'sumac', 'olive oil', 'lemon'],
    ['Toast pita until crisp.', 'Chop the vegetables.', 'Whisk sumac, lemon and olive oil.', 'Toss together just before serving.'], { country: 'LB', timeMinutes: 15 }),
  r('Kibbeh', 'middle_eastern', 'dinner', ['bulgur', 'ground beef', 'onion', 'pine nuts', 'cinnamon', 'cooking oil'],
    ['Soak bulgur and knead with beef.', 'Make a spiced filling with pine nuts.', 'Form stuffed shells.', 'Bake or fry until browned.'], { country: 'LB', timeMinutes: 60 }),
  r('Manakish Zaatar', 'middle_eastern', 'breakfast', ['wheat flour', 'zaatar', 'olive oil', 'sesame seeds'],
    ['Make a soft dough and rest.', 'Roll into rounds.', 'Spread with zaatar and olive oil.', 'Bake until the edges color.'], { country: 'LB', timeMinutes: 35 }),
  r('Baba Ganoush', 'middle_eastern', 'appetizer', ['eggplant', 'tahini', 'garlic', 'lemon', 'olive oil'],
    ['Char the eggplant until soft.', 'Scoop and mash the flesh.', 'Beat in tahini, garlic and lemon.', 'Finish with olive oil.'], { country: 'LB', timeMinutes: 30 }),
  r('Menemen', 'middle_eastern', 'breakfast', ['eggs', 'tomato', 'green pepper', 'onion', 'olive oil'],
    ['Soften pepper and onion in oil.', 'Add tomato and reduce.', 'Stir in beaten eggs.', 'Cook to a soft scramble.'], { country: 'TR', timeMinutes: 20 }),
  r('Red Lentil Soup', 'middle_eastern', 'supper', ['red lentils', 'onion', 'carrot', 'cumin', 'olive oil', 'lemon'],
    ['Soften onion and carrot.', 'Add lentils, cumin and water.', 'Simmer until collapsing.', 'Blend smooth and finish with lemon.'], { country: 'TR', timeMinutes: 35 }),
  r('Iskender Kebab', 'middle_eastern', 'dinner', ['lamb', 'yogurt', 'tomato', 'pita', 'butter'],
    ['Grill spiced lamb slices.', 'Lay over torn pita.', 'Top with tomato sauce and melted butter.', 'Serve with yogurt.'], { country: 'TR', timeMinutes: 45 }),
  r('Turkish Pilav', 'middle_eastern', 'lunch', ['rice', 'vermicelli noodles', 'butter', 'stock'],
    ['Toast vermicelli in butter.', 'Add rinsed rice.', 'Pour in hot stock.', 'Steam until tender, then fluff.'], { country: 'TR', timeMinutes: 30 }),
  r('Maqluba', 'middle_eastern', 'dinner', ['rice', 'chicken', 'eggplant', 'cauliflower', 'cinnamon', 'cooking oil'],
    ['Fry eggplant and cauliflower.', 'Layer with chicken and rice.', 'Cook covered until set.', 'Invert the pot to serve.'], { country: 'PS', timeMinutes: 75 }),
  r('Muhammara', 'middle_eastern', 'appetizer', ['red pepper', 'walnuts', 'pomegranate molasses', 'breadcrumbs', 'olive oil'],
    ['Roast and peel the peppers.', 'Blend with walnuts and breadcrumbs.', 'Add pomegranate molasses.', 'Loosen with olive oil.'], { country: 'SY', timeMinutes: 25 }),
  r('Mansaf', 'middle_eastern', 'dinner', ['lamb', 'yogurt', 'rice', 'almonds', 'cooking oil'],
    ['Slow-cook lamb until tender.', 'Make a warm jameed yogurt sauce.', 'Spread rice on flatbread.', 'Top with lamb, sauce and almonds.'], { country: 'JO', timeMinutes: 100 }),
  r('Basbousa', 'middle_eastern', 'dessert', ['semolina', 'yogurt', 'coconut', 'sugar', 'butter'],
    ['Mix semolina with yogurt and coconut.', 'Bake until golden.', 'Soak in sugar syrup.', 'Cool and cut into diamonds.'], { country: 'EG', timeMinutes: 45 }),
  r('Knafeh', 'middle_eastern', 'dessert', ['kataifi pastry', 'wheat flour', 'cheese', 'sugar', 'pistachios'],
    ['Layer shredded pastry with butter.', 'Add a soft cheese center.', 'Bake until crisp and golden.', 'Soak in syrup and top with pistachios.'], { country: 'PS', timeMinutes: 50 }),

  /* ---------------- Mediterranean ---------------- */
  r('Grilled Lemon Fish', 'mediterranean', 'dinner', ['white fish', 'lemon', 'garlic', 'olive oil', 'oregano'],
    ['Marinate fish in lemon, garlic and oregano.', 'Grill until just cooked.', 'Rest briefly.', 'Finish with olive oil.'], { timeMinutes: 25 }),
  r('Greek Salad', 'mediterranean', 'appetizer', ['tomato', 'cucumber', 'feta', 'olives', 'onion', 'olive oil'],
    ['Chop tomato, cucumber and onion.', 'Add olives and feta.', 'Dress with olive oil and oregano.', 'Toss gently.'], { timeMinutes: 15 }),
  r('Chickpea Stew', 'mediterranean', 'lunch', ['chickpeas', 'tomato', 'onion', 'garlic', 'spinach', 'olive oil'],
    ['Soften onion and garlic in olive oil.', 'Add tomato and chickpeas.', 'Simmer until rich.', 'Wilt in spinach.'], { timeMinutes: 35 }),
  r('Pasta Pomodoro', 'mediterranean', 'dinner', ['pasta', 'tomato', 'garlic', 'basil', 'olive oil'],
    ['Simmer a simple tomato-garlic sauce.', 'Cook pasta al dente.', 'Toss together with basil.', 'Finish with olive oil.'], { timeMinutes: 25 }),
  r('White Bean Breakfast Skillet', 'mediterranean', 'breakfast', ['white beans', 'tomato', 'onion', 'olive oil', 'paprika'],
    ['Soften onion in olive oil.', 'Add tomato and paprika.', 'Stir in white beans.', 'Simmer and serve with bread.'], { timeMinutes: 25 }),
  r('Roasted Vegetable Bowl', 'mediterranean', 'lunch', ['zucchini', 'bell pepper', 'chickpeas', 'couscous', 'olive oil', 'lemon'],
    ['Roast vegetables and chickpeas.', 'Steam couscous.', 'Combine in a bowl.', 'Dress with lemon and olive oil.'], { timeMinutes: 35 }),
  r('Yogurt with Honey and Fruit', 'mediterranean', 'dessert', ['yogurt', 'honey', 'orange', 'walnuts'],
    ['Spoon yogurt into bowls.', 'Top with orange segments.', 'Drizzle with honey.', 'Scatter walnuts.'], { timeMinutes: 5 }),

  /* ---------------- East Asian ---------------- */
  r('Chicken Teriyaki', 'east_asian', 'dinner', ['chicken', 'soy sauce', 'ginger', 'garlic', 'sugar', 'rice'],
    ['Sear chicken until golden.', 'Add a soy-ginger glaze.', 'Reduce until glossy.', 'Serve over rice.'], { timeMinutes: 25 }),
  r('Miso Soup', 'east_asian', 'breakfast', ['miso', 'tofu', 'scallion', 'seaweed'],
    ['Warm dashi or water.', 'Whisk in miso.', 'Add tofu and seaweed.', 'Finish with scallion.'], { timeMinutes: 15 }),
  r('Vegetable Bibimbap', 'east_asian', 'lunch', ['rice', 'spinach', 'carrot', 'egg', 'sesame oil', 'gochujang'],
    ['Cook rice and assorted vegetables.', 'Fry an egg.', 'Arrange over rice.', 'Serve with gochujang and sesame oil.'], { timeMinutes: 35 }),
  r('Tofu Stir-fry', 'east_asian', 'dinner', ['tofu', 'broccoli', 'garlic', 'ginger', 'soy sauce', 'sesame oil'],
    ['Pan-fry tofu until golden.', 'Stir-fry broccoli with aromatics.', 'Add soy sauce.', 'Toss and finish with sesame oil.'], { timeMinutes: 25 }),
  r('Edamame', 'east_asian', 'appetizer', ['edamame', 'salt'],
    ['Boil edamame in salted water.', 'Drain.', 'Toss with flaky salt.', 'Serve warm.'], { timeMinutes: 10 }),
  r('Matcha Fruit Bowl', 'east_asian', 'dessert', ['banana', 'orange', 'honey'],
    ['Slice fruit into a bowl.', 'Drizzle lightly with honey.', 'Chill briefly.', 'Serve.'], { timeMinutes: 10 }),

  /* ---------------- American ---------------- */
  r('Grilled Chicken and Veg', 'american', 'dinner', ['chicken', 'zucchini', 'bell pepper', 'olive oil', 'black pepper'],
    ['Season and grill chicken.', 'Grill the vegetables alongside.', 'Rest the chicken.', 'Plate together.'], { timeMinutes: 30 }),
  r('Turkey Chili', 'american', 'lunch', ['ground turkey', 'kidney beans', 'tomato', 'onion', 'cumin', 'paprika'],
    ['Brown turkey with onion.', 'Add tomato, beans and spices.', 'Simmer until thick.', 'Serve hot.'], { timeMinutes: 45 }),
  r('Veggie Omelette', 'american', 'breakfast', ['eggs', 'spinach', 'tomato', 'cheese', 'butter'],
    ['Whisk eggs.', 'Cook gently in butter.', 'Add spinach, tomato and cheese.', 'Fold and serve.'], { timeMinutes: 15 }),
  r('Bean Burrito Bowl', 'american', 'lunch', ['rice', 'black beans', 'corn', 'tomato', 'avocado', 'lime'],
    ['Build a base of rice and beans.', 'Add corn and tomato.', 'Top with avocado.', 'Finish with lime.'], { timeMinutes: 20 }),
  r('Baked Salmon', 'american', 'dinner', ['salmon', 'lemon', 'garlic', 'olive oil', 'black pepper'],
    ['Season salmon with lemon and garlic.', 'Bake until just flaky.', 'Rest briefly.', 'Serve with greens.'], { timeMinutes: 25 }),
  r('Fruit and Yogurt Parfait', 'american', 'dessert', ['yogurt', 'mixed berries', 'honey', 'oats'],
    ['Layer yogurt and berries.', 'Add a little honey.', 'Top with oats.', 'Chill and serve.'], { timeMinutes: 10 }),

  /* ---------------- European ---------------- */
  r('Chicken Cacciatore', 'european', 'dinner', ['chicken', 'tomato', 'onion', 'bell pepper', 'garlic', 'olive oil'],
    ['Brown chicken pieces.', 'Soften onion, pepper and garlic.', 'Add tomato and braise.', 'Serve with bread.'], { timeMinutes: 50 }),
  r('Vegetable Frittata', 'european', 'breakfast', ['eggs', 'potato', 'onion', 'spinach', 'olive oil'],
    ['Sauté potato and onion.', 'Add whisked eggs and spinach.', 'Cook until set.', 'Finish under a grill.'], { timeMinutes: 30 }),
  r('White Bean Soup', 'european', 'lunch', ['white beans', 'carrot', 'onion', 'garlic', 'olive oil', 'thyme'],
    ['Soften onion, carrot and garlic.', 'Add beans and stock.', 'Simmer with thyme.', 'Blend partly and serve.'], { timeMinutes: 40 }),
  r('Pan-Roasted Pork', 'european', 'dinner', ['pork', 'potato', 'garlic', 'rosemary', 'olive oil'],
    ['Sear pork with garlic and rosemary.', 'Roast with potatoes.', 'Rest the meat.', 'Slice and serve.'], { timeMinutes: 45 }),
  r('Lentil Stew', 'european', 'lunch', ['lentils', 'carrot', 'celery', 'onion', 'tomato', 'olive oil'],
    ['Soften the vegetables.', 'Add lentils and tomato.', 'Simmer until tender.', 'Season and serve.'], { timeMinutes: 40 }),
  r('Baked Apple', 'european', 'dessert', ['apple', 'butter', 'cinnamon', 'oats', 'honey'],
    ['Core the apples.', 'Fill with oats, butter and cinnamon.', 'Bake until soft.', 'Drizzle with honey.'], { timeMinutes: 35 }),

  /* ---------------- Latin ---------------- */
  r('Chicken Tinga Tacos', 'latin', 'dinner', ['chicken', 'tomato', 'onion', 'chipotle', 'corn tortilla', 'lime'],
    ['Cook and shred chicken.', 'Blend a smoky tomato-chipotle sauce.', 'Simmer chicken in the sauce.', 'Serve in warm tortillas with lime.'], { timeMinutes: 35 }),
  r('Black Bean Bowl', 'latin', 'lunch', ['black beans', 'rice', 'corn', 'tomato', 'avocado', 'lime'],
    ['Warm beans with spices.', 'Build over rice.', 'Add corn and tomato.', 'Top with avocado and lime.'], { timeMinutes: 20 }),
  r('Huevos Rancheros', 'latin', 'breakfast', ['eggs', 'corn tortilla', 'tomato', 'beans', 'chili'],
    ['Warm tortillas.', 'Fry eggs.', 'Top with a tomato-chili salsa.', 'Serve with beans.'], { timeMinutes: 20 }),
  r('Fish Ceviche', 'latin', 'appetizer', ['white fish', 'lime', 'onion', 'tomato', 'coriander', 'chili'],
    ['Dice fish finely.', 'Cure in lime juice.', 'Mix in onion, tomato and chili.', 'Finish with coriander.'], { timeMinutes: 25 }),
  r('Vegetable Quesadilla', 'latin', 'supper', ['wheat tortilla', 'cheese', 'bell pepper', 'onion', 'corn'],
    ['Sauté pepper, onion and corn.', 'Fill a tortilla with cheese and veg.', 'Griddle until melting.', 'Cut and serve.'], { timeMinutes: 20 }),
  r('Grilled Pineapple', 'latin', 'dessert', ['pineapple', 'butter', 'cinnamon', 'sugar'],
    ['Slice pineapple.', 'Brush with butter.', 'Grill until caramelized.', 'Dust with cinnamon sugar.'], { timeMinutes: 15 }),

  /* ---------------- African ---------------- */
  r('Chicken Peanut Stew', 'african', 'dinner', ['chicken', 'peanuts', 'tomato', 'onion', 'ginger', 'cooking oil'],
    ['Brown chicken with onion and ginger.', 'Add tomato and peanut butter.', 'Simmer until rich.', 'Serve with rice.'], { timeMinutes: 50 }),
  r('Jollof Rice', 'african', 'lunch', ['rice', 'tomato', 'onion', 'bell pepper', 'cooking oil', 'spices'],
    ['Blend a tomato-pepper base.', 'Fry it down with onion.', 'Add rice and stock.', 'Steam until done.'], { timeMinutes: 50 }),
  r('Berbere Lentils', 'african', 'lunch', ['lentils', 'onion', 'garlic', 'ginger', 'berbere', 'cooking oil'],
    ['Soften onion, garlic and ginger.', 'Bloom berbere spice.', 'Add lentils and water.', 'Simmer until soft.'], { timeMinutes: 40 }),
  r('Shakshuka-style Eggs', 'african', 'breakfast', ['eggs', 'tomato', 'onion', 'bell pepper', 'cumin'],
    ['Cook a spiced tomato-pepper base.', 'Make wells for eggs.', 'Cover until set.', 'Serve with bread.'], { timeMinutes: 25 }),
  r('Spiced Fruit Salad', 'african', 'dessert', ['mango', 'banana', 'orange', 'lime', 'mint'],
    ['Chop the fruit.', 'Toss with lime.', 'Add torn mint.', 'Chill and serve.'], { timeMinutes: 10 }),
  r('Egusi Soup', 'african', 'dinner', ['egusi seeds', 'spinach', 'beef', 'palm oil', 'onion', 'scotch bonnet'],
    ['Brown beef with onion.', 'Stir ground egusi into hot palm oil.', 'Add stock and simmer.', 'Fold in spinach and pepper.'], { country: 'NG', timeMinutes: 55 }),
  r('Suya', 'african', 'supper', ['beef', 'peanuts', 'paprika', 'ginger', 'cayenne', 'cooking oil'],
    ['Grind peanuts with spices into suya rub.', 'Coat thin beef strips.', 'Thread onto skewers.', 'Grill over high heat.'], { country: 'NG', timeMinutes: 30 }),
  r('Pepper Soup', 'african', 'supper', ['goat meat', 'pepper soup spice', 'onion', 'scotch bonnet', 'ginger'],
    ['Boil goat with onion and ginger.', 'Add pepper soup spice.', 'Simmer until tender.', 'Finish with scotch bonnet heat.'], { country: 'NG', timeMinutes: 70 }),
  r('Moin Moin', 'african', 'breakfast', ['black-eyed peas', 'red pepper', 'onion', 'palm oil', 'eggs'],
    ['Blend soaked peas with pepper and onion.', 'Beat in palm oil and egg.', 'Pour into cups.', 'Steam until set.'], { country: 'NG', timeMinutes: 60 }),
  r('Efo Riro', 'african', 'lunch', ['spinach', 'palm oil', 'red pepper', 'beef', 'onion'],
    ['Fry pepper blend in palm oil.', 'Add cooked beef.', 'Stir in chopped spinach.', 'Simmer briefly and serve with rice.'], { country: 'NG', timeMinutes: 40 }),
  r('Doro Wat', 'african', 'dinner', ['chicken', 'berbere', 'onion', 'eggs', 'ghee', 'garlic'],
    ['Slow-cook onions until jammy.', 'Bloom berbere in ghee.', 'Add chicken and simmer.', 'Nestle in boiled eggs.'], { country: 'ET', timeMinutes: 80 }),
  r('Shiro', 'african', 'lunch', ['chickpea flour', 'berbere', 'onion', 'garlic', 'cooking oil'],
    ['Soften onion and garlic.', 'Stir in berbere.', 'Whisk in chickpea flour and water.', 'Simmer to a smooth stew.'], { country: 'ET', timeMinutes: 30 }),
  r('Misir Wot', 'african', 'lunch', ['red lentils', 'berbere', 'onion', 'garlic', 'cooking oil'],
    ['Cook down onion and garlic.', 'Add berbere.', 'Stir in lentils and water.', 'Simmer until thick.'], { country: 'ET', timeMinutes: 40 }),
  r('Gomen', 'african', 'lunch', ['collard greens', 'garlic', 'ginger', 'onion', 'cooking oil'],
    ['Sweat onion, garlic and ginger.', 'Add chopped collards.', 'Splash in water.', 'Steam until just tender.'], { country: 'ET', timeMinutes: 25 }),
  r('Waakye', 'african', 'lunch', ['rice', 'black-eyed peas', 'onion', 'cooking oil'],
    ['Cook peas until nearly soft.', 'Add rice and water.', 'Steam together.', 'Serve with pepper sauce.'], { country: 'GH', timeMinutes: 50 }),
  r('Kelewele', 'african', 'supper', ['plantain', 'ginger', 'cayenne', 'cooking oil'],
    ['Cube ripe plantain.', 'Toss with ginger and cayenne.', 'Fry until caramelized.', 'Drain and serve hot.'], { country: 'GH', timeMinutes: 20 }),
  r('Groundnut Soup', 'african', 'dinner', ['chicken', 'peanuts', 'tomato', 'onion', 'ginger'],
    ['Brown chicken with onion and ginger.', 'Add tomato and peanut paste.', 'Pour in stock.', 'Simmer until rich and serve with rice.'], { country: 'GH', timeMinutes: 55 }),
  r('Thieboudienne', 'african', 'dinner', ['white fish', 'rice', 'tomato', 'cassava', 'carrot', 'cooking oil'],
    ['Stuff and sear the fish.', 'Build a tomato base.', 'Simmer vegetables in it.', 'Cook rice in the broth.'], { country: 'SN', timeMinutes: 75 }),
  r('Chicken Yassa', 'african', 'dinner', ['chicken', 'onion', 'lemon', 'mustard', 'cooking oil'],
    ['Marinate chicken in lemon and mustard.', 'Sear, then set aside.', 'Slow-cook a mountain of onions.', 'Return chicken and simmer.'], { country: 'SN', timeMinutes: 60 }),
  r('Ugali with Sukuma', 'african', 'lunch', ['cornmeal', 'collard greens', 'onion', 'tomato', 'cooking oil'],
    ['Stir cornmeal into boiling water.', 'Cook to a firm ugali.', 'Fry greens with onion and tomato.', 'Serve together.'], { country: 'KE', timeMinutes: 30 }),
  r('Nyama Choma', 'african', 'dinner', ['goat meat', 'garlic', 'lemon', 'cooking oil'],
    ['Marinate goat with garlic and lemon.', 'Grill slowly over coals.', 'Turn until charred and tender.', 'Rest, then chop to serve.'], { country: 'KE', timeMinutes: 70 }),
  r('Bobotie', 'african', 'dinner', ['ground beef', 'curry powder', 'bread', 'eggs', 'raisins', 'onion'],
    ['Soften onion and brown beef.', 'Add curry powder and raisins.', 'Soak bread, mix in.', 'Top with egg custard and bake.'], { country: 'ZA', timeMinutes: 65 }),
  r('Chakalaka', 'african', 'supper', ['beans', 'carrot', 'bell pepper', 'onion', 'curry powder', 'tomato'],
    ['Fry onion, pepper and carrot.', 'Add curry powder.', 'Stir in tomato and beans.', 'Simmer to a relish.'], { country: 'ZA', timeMinutes: 30 }),
  r('Lamb Maafe', 'african', 'dinner', ['lamb', 'peanuts', 'tomato', 'sweet potato', 'onion'],
    ['Brown lamb with onion.', 'Stir in peanut paste and tomato.', 'Add sweet potato and water.', 'Simmer until thick.'], { country: 'ML', timeMinutes: 75 }),
  r('Mandazi', 'african', 'dessert', ['wheat flour', 'coconut milk', 'cardamom', 'sugar'],
    ['Make a soft cardamom dough.', 'Roll and cut triangles.', 'Fry until puffed and golden.', 'Dust with sugar.'], { country: 'KE', timeMinutes: 40 }),
  r('Puff Puff', 'african', 'dessert', ['wheat flour', 'sugar', 'yeast', 'nutmeg', 'cooking oil'],
    ['Mix a sweet yeast batter.', 'Prove until bubbly.', 'Drop spoonfuls into hot oil.', 'Fry to golden balls.'], { country: 'NG', timeMinutes: 45 }),
];

let memo: TaggedRecipe[] | null = null;

/** The tagged corpus — computed once, deterministically, on first use. */
export function getCorpus(): TaggedRecipe[] {
  if (!memo) memo = RAW.map(tagRecipe);
  return memo;
}

/** Total seed-corpus size (for diagnostics / about screens). */
export const CORPUS_SIZE = RAW.length;
