/**
 * Full country → currency dataset for the onboarding picker and the local
 * grocery-budget estimate. Rates are APPROXIMATE (per 1 USD, ~2026) and only
 * power a rough "est." figure — never a payment — so they don't need to be
 * live. Currencies not in the rate table fall back to a USD-equivalent display.
 *
 * `region` is the suggested cuisine when a country is picked (user can change).
 */

import type { Region } from '@/types';

export interface Country {
  code: string; // ISO 3166-1 alpha-2
  label: string;
  currency: string; // ISO 4217
  region: Region;
}

// [code, label, currency, suggested cuisine region]
type Row = [string, string, string, Region];

const ROWS: Row[] = [
  // South Asia
  ['PK', 'Pakistan', 'PKR', 'south_asian'],
  ['IN', 'India', 'INR', 'south_asian'],
  ['BD', 'Bangladesh', 'BDT', 'south_asian'],
  ['LK', 'Sri Lanka', 'LKR', 'south_asian'],
  ['NP', 'Nepal', 'NPR', 'south_asian'],
  ['AF', 'Afghanistan', 'AFN', 'south_asian'],
  ['BT', 'Bhutan', 'BTN', 'south_asian'],
  ['MV', 'Maldives', 'MVR', 'south_asian'],
  // Middle East / MENA
  ['AE', 'United Arab Emirates', 'AED', 'middle_eastern'],
  ['SA', 'Saudi Arabia', 'SAR', 'middle_eastern'],
  ['QA', 'Qatar', 'QAR', 'middle_eastern'],
  ['KW', 'Kuwait', 'KWD', 'middle_eastern'],
  ['BH', 'Bahrain', 'BHD', 'middle_eastern'],
  ['OM', 'Oman', 'OMR', 'middle_eastern'],
  ['YE', 'Yemen', 'YER', 'middle_eastern'],
  ['IR', 'Iran', 'IRR', 'middle_eastern'],
  ['IQ', 'Iraq', 'IQD', 'middle_eastern'],
  ['JO', 'Jordan', 'JOD', 'middle_eastern'],
  ['LB', 'Lebanon', 'LBP', 'middle_eastern'],
  ['SY', 'Syria', 'SYP', 'middle_eastern'],
  ['IL', 'Israel', 'ILS', 'middle_eastern'],
  ['PS', 'Palestine', 'ILS', 'middle_eastern'],
  ['EG', 'Egypt', 'EGP', 'middle_eastern'],
  ['LY', 'Libya', 'LYD', 'middle_eastern'],
  ['TN', 'Tunisia', 'TND', 'middle_eastern'],
  ['DZ', 'Algeria', 'DZD', 'middle_eastern'],
  ['MA', 'Morocco', 'MAD', 'middle_eastern'],
  ['SD', 'Sudan', 'SDG', 'middle_eastern'],
  // Mediterranean / Southern Europe
  ['TR', 'Türkiye', 'TRY', 'mediterranean'],
  ['GR', 'Greece', 'EUR', 'mediterranean'],
  ['IT', 'Italy', 'EUR', 'mediterranean'],
  ['ES', 'Spain', 'EUR', 'mediterranean'],
  ['PT', 'Portugal', 'EUR', 'mediterranean'],
  ['CY', 'Cyprus', 'EUR', 'mediterranean'],
  ['MT', 'Malta', 'EUR', 'mediterranean'],
  // East / Southeast Asia
  ['CN', 'China', 'CNY', 'east_asian'],
  ['JP', 'Japan', 'JPY', 'east_asian'],
  ['KR', 'South Korea', 'KRW', 'east_asian'],
  ['TW', 'Taiwan', 'TWD', 'east_asian'],
  ['HK', 'Hong Kong', 'HKD', 'east_asian'],
  ['TH', 'Thailand', 'THB', 'east_asian'],
  ['VN', 'Vietnam', 'VND', 'east_asian'],
  ['ID', 'Indonesia', 'IDR', 'east_asian'],
  ['MY', 'Malaysia', 'MYR', 'east_asian'],
  ['PH', 'Philippines', 'PHP', 'east_asian'],
  ['SG', 'Singapore', 'SGD', 'east_asian'],
  ['MM', 'Myanmar', 'MMK', 'east_asian'],
  ['KH', 'Cambodia', 'KHR', 'east_asian'],
  ['LA', 'Laos', 'LAK', 'east_asian'],
  ['MN', 'Mongolia', 'MNT', 'east_asian'],
  // Latin America
  ['MX', 'Mexico', 'MXN', 'latin'],
  ['BR', 'Brazil', 'BRL', 'latin'],
  ['AR', 'Argentina', 'ARS', 'latin'],
  ['CO', 'Colombia', 'COP', 'latin'],
  ['CL', 'Chile', 'CLP', 'latin'],
  ['PE', 'Peru', 'PEN', 'latin'],
  ['VE', 'Venezuela', 'VES', 'latin'],
  ['EC', 'Ecuador', 'USD', 'latin'],
  ['GT', 'Guatemala', 'GTQ', 'latin'],
  ['CU', 'Cuba', 'CUP', 'latin'],
  ['BO', 'Bolivia', 'BOB', 'latin'],
  ['DO', 'Dominican Republic', 'DOP', 'latin'],
  ['HN', 'Honduras', 'HNL', 'latin'],
  ['PY', 'Paraguay', 'PYG', 'latin'],
  ['SV', 'El Salvador', 'USD', 'latin'],
  ['NI', 'Nicaragua', 'NIO', 'latin'],
  ['CR', 'Costa Rica', 'CRC', 'latin'],
  ['PA', 'Panama', 'USD', 'latin'],
  ['UY', 'Uruguay', 'UYU', 'latin'],
  // Africa (sub-Saharan)
  ['NG', 'Nigeria', 'NGN', 'african'],
  ['ZA', 'South Africa', 'ZAR', 'african'],
  ['KE', 'Kenya', 'KES', 'african'],
  ['GH', 'Ghana', 'GHS', 'african'],
  ['ET', 'Ethiopia', 'ETB', 'african'],
  ['TZ', 'Tanzania', 'TZS', 'african'],
  ['UG', 'Uganda', 'UGX', 'african'],
  ['CM', 'Cameroon', 'XAF', 'african'],
  ['CI', "Côte d'Ivoire", 'XOF', 'african'],
  ['SN', 'Senegal', 'XOF', 'african'],
  ['ZW', 'Zimbabwe', 'USD', 'african'],
  ['ZM', 'Zambia', 'ZMW', 'african'],
  ['RW', 'Rwanda', 'RWF', 'african'],
  ['SO', 'Somalia', 'SOS', 'african'],
  // North America, Europe, Oceania, rest (cuisine 'none' = everyday)
  ['US', 'United States', 'USD', 'none'],
  ['CA', 'Canada', 'CAD', 'none'],
  ['GB', 'United Kingdom', 'GBP', 'none'],
  ['IE', 'Ireland', 'EUR', 'none'],
  ['FR', 'France', 'EUR', 'none'],
  ['DE', 'Germany', 'EUR', 'none'],
  ['NL', 'Netherlands', 'EUR', 'none'],
  ['BE', 'Belgium', 'EUR', 'none'],
  ['CH', 'Switzerland', 'CHF', 'none'],
  ['AT', 'Austria', 'EUR', 'none'],
  ['SE', 'Sweden', 'SEK', 'none'],
  ['NO', 'Norway', 'NOK', 'none'],
  ['DK', 'Denmark', 'DKK', 'none'],
  ['FI', 'Finland', 'EUR', 'none'],
  ['PL', 'Poland', 'PLN', 'none'],
  ['CZ', 'Czechia', 'CZK', 'none'],
  ['RO', 'Romania', 'RON', 'none'],
  ['HU', 'Hungary', 'HUF', 'none'],
  ['UA', 'Ukraine', 'UAH', 'none'],
  ['RU', 'Russia', 'RUB', 'none'],
  ['AU', 'Australia', 'AUD', 'none'],
  ['NZ', 'New Zealand', 'NZD', 'none'],
];

export const COUNTRIES: Country[] = ROWS.map(([code, label, currency, region]) => ({
  code,
  label,
  currency,
  region,
})).sort((a, b) => a.label.localeCompare(b.label));

/** Symbol + approx units per 1 USD for each currency used above. */
export const CURRENCY: Record<string, { symbol: string; usdRate: number }> = {
  USD: { symbol: '$', usdRate: 1 },
  EUR: { symbol: '€', usdRate: 0.92 },
  GBP: { symbol: '£', usdRate: 0.79 },
  JPY: { symbol: '¥', usdRate: 150 },
  CNY: { symbol: '¥', usdRate: 7.2 },
  INR: { symbol: '₹', usdRate: 83 },
  PKR: { symbol: '₨', usdRate: 278 },
  BDT: { symbol: '৳', usdRate: 118 },
  LKR: { symbol: 'Rs', usdRate: 300 },
  NPR: { symbol: 'रू', usdRate: 133 },
  AFN: { symbol: '؋', usdRate: 70 },
  BTN: { symbol: 'Nu.', usdRate: 83 },
  MVR: { symbol: 'Rf', usdRate: 15.4 },
  AED: { symbol: 'د.إ', usdRate: 3.67 },
  SAR: { symbol: '﷼', usdRate: 3.75 },
  QAR: { symbol: 'ر.ق', usdRate: 3.64 },
  KWD: { symbol: 'د.ك', usdRate: 0.31 },
  BHD: { symbol: '.د.ب', usdRate: 0.38 },
  OMR: { symbol: 'ر.ع.', usdRate: 0.385 },
  YER: { symbol: '﷼', usdRate: 250 },
  IRR: { symbol: '﷼', usdRate: 42000 },
  IQD: { symbol: 'ع.د', usdRate: 1310 },
  JOD: { symbol: 'د.ا', usdRate: 0.71 },
  LBP: { symbol: 'ل.ل', usdRate: 89000 },
  SYP: { symbol: '£', usdRate: 13000 },
  ILS: { symbol: '₪', usdRate: 3.7 },
  EGP: { symbol: 'E£', usdRate: 48 },
  LYD: { symbol: 'ل.د', usdRate: 4.8 },
  TND: { symbol: 'د.ت', usdRate: 3.1 },
  DZD: { symbol: 'د.ج', usdRate: 134 },
  MAD: { symbol: 'د.م.', usdRate: 10 },
  SDG: { symbol: 'ج.س.', usdRate: 600 },
  TRY: { symbol: '₺', usdRate: 32 },
  KRW: { symbol: '₩', usdRate: 1350 },
  TWD: { symbol: 'NT$', usdRate: 32 },
  HKD: { symbol: 'HK$', usdRate: 7.8 },
  THB: { symbol: '฿', usdRate: 36 },
  VND: { symbol: '₫', usdRate: 25000 },
  IDR: { symbol: 'Rp', usdRate: 15800 },
  MYR: { symbol: 'RM', usdRate: 4.4 },
  PHP: { symbol: '₱', usdRate: 58 },
  SGD: { symbol: 'S$', usdRate: 1.35 },
  MMK: { symbol: 'K', usdRate: 2100 },
  KHR: { symbol: '៛', usdRate: 4100 },
  LAK: { symbol: '₭', usdRate: 21000 },
  MNT: { symbol: '₮', usdRate: 3400 },
  MXN: { symbol: 'Mex$', usdRate: 18 },
  BRL: { symbol: 'R$', usdRate: 5.1 },
  ARS: { symbol: '$', usdRate: 950 },
  COP: { symbol: '$', usdRate: 3900 },
  CLP: { symbol: '$', usdRate: 950 },
  PEN: { symbol: 'S/', usdRate: 3.75 },
  VES: { symbol: 'Bs', usdRate: 36 },
  GTQ: { symbol: 'Q', usdRate: 7.8 },
  CUP: { symbol: '$', usdRate: 24 },
  BOB: { symbol: 'Bs', usdRate: 6.9 },
  DOP: { symbol: 'RD$', usdRate: 59 },
  HNL: { symbol: 'L', usdRate: 24.7 },
  PYG: { symbol: '₲', usdRate: 7400 },
  NIO: { symbol: 'C$', usdRate: 36.7 },
  CRC: { symbol: '₡', usdRate: 515 },
  UYU: { symbol: '$U', usdRate: 39 },
  NGN: { symbol: '₦', usdRate: 1550 },
  ZAR: { symbol: 'R', usdRate: 18 },
  KES: { symbol: 'KSh', usdRate: 130 },
  GHS: { symbol: '₵', usdRate: 15 },
  ETB: { symbol: 'Br', usdRate: 57 },
  TZS: { symbol: 'TSh', usdRate: 2600 },
  UGX: { symbol: 'USh', usdRate: 3700 },
  XAF: { symbol: 'FCFA', usdRate: 600 },
  XOF: { symbol: 'CFA', usdRate: 600 },
  ZMW: { symbol: 'ZK', usdRate: 26 },
  RWF: { symbol: 'FRw', usdRate: 1300 },
  SOS: { symbol: 'Sh', usdRate: 571 },
  CAD: { symbol: 'C$', usdRate: 1.37 },
  CHF: { symbol: 'CHF', usdRate: 0.88 },
  SEK: { symbol: 'kr', usdRate: 10.6 },
  NOK: { symbol: 'kr', usdRate: 10.7 },
  DKK: { symbol: 'kr', usdRate: 6.9 },
  PLN: { symbol: 'zł', usdRate: 4 },
  CZK: { symbol: 'Kč', usdRate: 23 },
  RON: { symbol: 'lei', usdRate: 4.6 },
  HUF: { symbol: 'Ft', usdRate: 360 },
  UAH: { symbol: '₴', usdRate: 41 },
  RUB: { symbol: '₽', usdRate: 92 },
  AUD: { symbol: 'A$', usdRate: 1.52 },
  NZD: { symbol: 'NZ$', usdRate: 1.64 },
};

/** Turn an ISO alpha-2 code into its flag emoji (regional indicator letters). */
export function flagEmoji(code: string): string {
  if (code.length !== 2) return '🏳️';
  const A = 0x1f1e6;
  const base = 'A'.charCodeAt(0);
  return String.fromCodePoint(A + (code.charCodeAt(0) - base), A + (code.charCodeAt(1) - base));
}
