import { useRouter } from 'expo-router';
import type { ReactNode } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { Art } from '@/components/art';
import { Body, Heading, PressableScale, Screen, Small } from '@/components/ui';
import { Spacing, Type } from '@/constants/theme';
import { usePalette } from '@/theme/use-theme';

const UPDATED = 'July 2026';

export default function Privacy() {
  const router = useRouter();
  const palette = usePalette();

  return (
    <Screen art={Art.fruits} wide>
      <View style={styles.top}>
        <PressableScale onPress={() => router.back()} to={0.9}>
          <View style={[styles.back, { borderColor: palette.border, backgroundColor: palette.card }]}>
            <Text style={{ fontFamily: Type.bodySemibold, fontSize: 18, color: palette.text }}>‹</Text>
          </View>
        </PressableScale>
        <Heading>Privacy Policy</Heading>
      </View>

      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingVertical: Spacing.four, gap: Spacing.four, maxWidth: 680 }}>
        <Small color={palette.textSecondary}>Last updated: {UPDATED}</Small>

        <Section title="What we collect">
          <Body color={palette.textSecondary}>
            Your account email (via Supabase Auth), the household and member profiles you create — names, age bands,
            and dietary constraints such as allergies, medical, religious, or lifestyle diets — and the meal plans
            and grocery lists generated for you. We also record basic usage events (sign-up, onboarding completed,
            plan generated, paywall viewed, subscribed) for product analytics. We do not send the contents of your
            dietary or health data to analytics — only that an event happened.
          </Body>
        </Section>

        <Section title="How we use it">
          <Body color={palette.textSecondary}>
            Meal plans are generated by our own deterministic engine, running entirely on our servers and in the app
            — your dietary data is never sent to a third-party AI model to generate a plan. Your household's
            constraints are merged into a hard-exclude list, a soft-avoid list, and an allow-list, which drive a
            recipe engine we built and control. Every plan is then re-checked deterministically in our own code
            against your hard-exclude list before it is ever shown to you.
          </Body>
        </Section>

        <Section title="Marketing emails">
          <Body color={palette.textSecondary}>
            We only send marketing or promotional email if you explicitly opt in (a checkbox on the sign-in screen,
            unchecked by default). You can withdraw consent at any time from Settings, or via the unsubscribe link in
            any marketing email. Transactional email (e.g. magic-link sign-in) is sent regardless, since it's required
            to use the service.
          </Body>
        </Section>

        <Section title="Community content">
          <Body color={palette.textSecondary}>
            If you make your profile public, your posts, comments, and shared recipes are visible to other users.
            Submitted content is automatically screened for prohibited language and spam before publishing, and any
            post can be reported by other users; content reported by multiple users is automatically hidden pending
            review. Community content is separate from your private household and dietary data, which is never made
            public.
          </Body>
        </Section>

        <Section title="Who we share it with">
          <Body color={palette.textSecondary}>
            Supabase hosts our database and authentication. Freemius processes web subscription payments; RevenueCat
            will process mobile subscriptions once mobile apps ship. Mixpanel receives anonymous product usage events
            only. We do not sell your data.
          </Body>
        </Section>

        <Section title="Your data, your control">
          <Body color={palette.textSecondary}>
            Row Level Security is enabled on every table — you can only read or write data tied to your own account.
            You can edit or remove members and household data any time from Settings. To request full account
            deletion, contact us below.
          </Body>
        </Section>

        <Section title="Contact">
          <Body color={palette.textSecondary}>Questions about this policy? Email hello@mealmesh.app.</Body>
        </Section>
      </ScrollView>
    </Screen>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  const palette = usePalette();
  return (
    <View style={{ gap: 6 }}>
      <Text style={{ fontFamily: Type.bodySemibold, fontSize: 16, color: palette.text }}>{title}</Text>
      {children}
    </View>
  );
}

const styles = StyleSheet.create({
  top: { flexDirection: 'row', alignItems: 'center', gap: Spacing.three, paddingTop: Spacing.three },
  back: { width: 40, height: 40, borderRadius: 999, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
});
